CREATE TABLE IF NOT EXISTS events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    booking_id INT UNSIGNED DEFAULT NULL,
    created_by_role ENUM('client','taker') NOT NULL,
    created_by_id INT UNSIGNED NOT NULL,
    client_id INT UNSIGNED DEFAULT NULL,
    taker_id INT UNSIGNED DEFAULT NULL,
    title VARCHAR(180) NOT NULL,
    event_date DATE NOT NULL,
    day_part ENUM('full_day','first_half','second_half') NOT NULL DEFAULT 'full_day',
    service_type VARCHAR(64) DEFAULT NULL,
    location VARCHAR(255) DEFAULT NULL,
    client_name VARCHAR(150) DEFAULT NULL,
    client_phone VARCHAR(20) DEFAULT NULL,
    taker_name VARCHAR(150) DEFAULT NULL,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    paid_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    notes TEXT DEFAULT NULL,
    status ENUM('Upcoming','Pending','Confirmed','Completed','Cancelled') NOT NULL DEFAULT 'Upcoming',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_events_booking(booking_id),
    INDEX idx_events_actor(created_by_role, created_by_id, event_date),
    INDEX idx_events_client(client_id, event_date),
    INDEX idx_events_taker(taker_id, event_date),
    INDEX idx_events_status(status, event_date),
    CONSTRAINT fk_events_booking FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE SET NULL,
    CONSTRAINT fk_events_client FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE SET NULL,
    CONSTRAINT fk_events_taker FOREIGN KEY(taker_id) REFERENCES takers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
